In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [ ]:
vector = np.ones(20)*2**np.arange(1,21)/np.arange(1,21)
vector

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [ ]:
sums = np.sum(np.ones(6)*0.1**(3*np.arange(6))*0.2**(4*np.arange(6)))
sums

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [ ]:
array = np.zeros([8,8])
array[1::2 , 1::2] = 1
array[::2 , ::2] = 1
array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [ ]:
X = np.random.random((5, 2))
r=np.sqrt(X[:,0]**2+ X[:,1]**2)
p = np.array([r,np.arccos(X[:,0]/r)]).T
p

array([[0.72818118, 0.18004834],
       [0.45970355, 1.21948297],
       [1.36982409, 0.7698727 ],
       [0.90439494, 0.6327994 ],
       [1.00067217, 1.1540127 ]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [ ]:
X = np.random.random((10, 10))
print(X)
max = np.unravel_index(np.argmax(X),X.shape)
max



[[0.63425402 0.86502231 0.79271207 0.70672093 0.53475074 0.76394047
  0.1333636  0.30859278 0.71767384 0.87725731]
 [0.41999036 0.25529289 0.98115983 0.37353562 0.08919324 0.03397953
  0.06331034 0.26136179 0.39752713 0.72505388]
 [0.15148749 0.79288684 0.33178478 0.14878943 0.31226305 0.97729798
  0.24776224 0.24388603 0.32856088 0.40502253]
 [0.61432247 0.65306147 0.07325705 0.40506491 0.53195684 0.78278826
  0.50834135 0.31637766 0.58819891 0.93679534]
 [0.14639067 0.34340335 0.03420021 0.89179269 0.26244688 0.31717146
  0.75991261 0.03489356 0.58134091 0.85220077]
 [0.92662965 0.97099524 0.26565046 0.79288696 0.5624216  0.67949003
  0.42220745 0.34359961 0.94210864 0.30410092]
 [0.34976465 0.55422503 0.84407291 0.67919547 0.78800825 0.75541624
  0.68359516 0.37534822 0.12129546 0.39401033]
 [0.78297991 0.21406193 0.28073746 0.08912057 0.31236953 0.71286751
  0.12926057 0.6185299  0.11846003 0.9027477 ]
 [0.77336957 0.57236119 0.36693574 0.71077124 0.72688822 0.05458842
  0.37017982

(1, 2)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [ ]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
lin_norm = np.sqrt((X[:,0]- y[:,0])**2*(X[:,1]- y[:,1])**2)
np.argmin(lin_norm)



1

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
import random
x = np.array([random.uniform(-3,3) for i in range(20)])
x1 = x[x<0]**2+2*x[x<0]+6
x2 = x[(x>=0)&(x<=2)]+6
x3 = x[x>=2]**2 +4*x[x>=2]-4
np.concatenate([x1,x2,x3])


[ 2.90905931 -1.76091742 -1.87003066 -0.91290253  2.26025635 -2.57501715
 -0.1955666  -1.62191836 -2.51810782  2.66304994  0.62578652 -2.95818774
  1.67729132  1.39317706 -0.22894658 -2.82743599  0.46939343 -0.60884962
  1.42807743  0.80523158]


array([ 5.57899532,  5.75695335,  5.00758597,  7.48067901,  5.64711309,
        5.38678244,  7.30465136,  8.83449923,  5.59452337,  8.33952231,
        5.15299862,  6.62578652,  7.67729132,  7.39317706,  6.46939343,
        7.42807743,  6.80523158, 16.09886332, 10.14978421, 13.7440347 ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [ ]:
X = np.random.random((10, 10))
X - np.mean(X,axis=1)

array([[-0.35899068,  0.02944203,  0.31738356, -0.31045585,  0.09592864,
        -0.36133158,  0.38813106, -0.03042892, -0.37806595, -0.14306606],
       [ 0.34512409, -0.44051522,  0.42395589, -0.31396236,  0.30730047,
        -0.08657535, -0.5492996 ,  0.13030118,  0.16015981, -0.2227178 ],
       [-0.1050462 ,  0.28897668, -0.48518271,  0.01497755,  0.17613746,
        -0.33865073, -0.34982172,  0.61599675,  0.38532758,  0.17181699],
       [ 0.30447516, -0.0196721 ,  0.23007072, -0.45100378,  0.33147946,
        -0.20008094, -0.48223289,  0.58323153, -0.52901926,  0.16581259],
       [ 0.30539562, -0.13596709, -0.52065434,  0.27005134, -0.20597639,
         0.41538691, -0.01373659,  0.46254047, -0.23690701,  0.03705515],
       [ 0.33724758,  0.46003779, -0.159415  ,  0.31328827,  0.31643169,
         0.09429626,  0.00169306, -0.33645291, -0.27961114, -0.40638686],
       [ 0.24971234,  0.05656998,  0.02382473, -0.23022714, -0.44897575,
         0.2500934 ,  0.01800785,  0.61751758

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [ ]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(np.mean(X))
print(np.var(X))

5.015276010565441
3.9841219692385548


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [ ]:
X = np.zeros([5,5])
X=np.arange(5)+X
X=X+X.T
right = np.rot90(np.tri(5, 5, -1 ))*(X -5)
left = np.rot90(np.tri(5, 5, 0 ),3)* X
left+right

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [ ]:
def sample(x, c):
    s = np.sum(x)
    val = s * np.random.random(c)
    x = np.repeat(np.cumsum(x), c).reshape((len(x), c)) - val
    x[x>=0] = 0
    res = np.argmax(x,axis = 1)
    return res

x = [50, 3, 1, 7, 20]
с = 5
sample(x,c)

array([0, 0, 0, 0, 0])